# Generated by Django 5.0.7 on 2024-11-07 11:27

import BotCommerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotCommerce', '0003_productdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=255, verbose_name=BotCommerce.models.Category),
        ),
    ]
