# Generated by Django 5.0.7 on 2024-11-07 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotCommerce', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='BotCommerce.category'),
        ),
    ]
