# Generated by Django 5.0.7 on 2024-11-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotCommerce', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
