# Generated by Django 5.0.7 on 2024-11-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotCommerce', '0007_product_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PENDING_RECEIPT', 'Pending Receipt'), ('COMPLETED', 'Completed')], default='PENDING_PAYMENT', max_length=20),
        ),
    ]
